Repository GodGaji/GajiQuiz_Backend, pull requests merged in 2021-02, with the labels that each got.

#19 Revert : 카카오 OAuth2 로그인 기능 제거
  build.gradle
  src/main/java/kr/godgaji/gajiquiz/config/CustomOAuth2Provider.java
  src/main/java/kr/godgaji/gajiquiz/config/JpaConfig.java
  src/main/java/kr/godgaji/gajiquiz/config/SecurityConfig.java
  src/main/java/kr/godgaji/gajiquiz/domain/BaseEntity.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/Member.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/MemberRepository.java
  src/main/java/kr/godgaji/gajiquiz/domain/Role/Role.java
  src/main/java/kr/godgaji/gajiquiz/service/CustomOAuth2UserService.java
  src/main/java/kr/godgaji/gajiquiz/web/GlobalControllerAdvice.java
  src/main/java/kr/godgaji/gajiquiz/web/dto/OAuthAttributes.java
  src/main/java/kr/godgaji/gajiquiz/web/dto/SessionUser.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.properties
  src/test/java/kr/godgaji/gajiquiz/repository/MemberRepositoryTest.java
  src/test/resources/application-oauth.properties
  src/test/resources/application.properties
Labels: :egg: refactor

#20 feat : API 문서 자동화 설정 [#10]
  build.gradle
  src/main/java/kr/godgaji/gajiquiz/config/SecurityConfig.java
  src/main/java/kr/godgaji/gajiquiz/config/SwaggerConfig.java
Labels: :eggplant: feature

#21 feat : coverage 설정 [#12]
  .github/workflows/gradle.yml
  README.md
  build.gradle
  src/test/java/kr/godgaji/gajiquiz/GajiquizApplicationTests.java
Labels: :eggplant: feature

#22 feat : Spring Boot log 설정 [#13]
  .gitignore
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/log4j2.yml
Labels: :eggplant: feature

#26 feat,chore : 도메인 추가,coverage수정,테코추가 [#23]
  lombok.config
  src/main/java/kr/godgaji/gajiquiz/config/SwaggerConfig.java
  src/main/java/kr/godgaji/gajiquiz/domain/Answer/Answer.java
  src/main/java/kr/godgaji/gajiquiz/domain/Answer/AnswerRepository.java
  src/main/java/kr/godgaji/gajiquiz/domain/BaseEntity.java
  src/main/java/kr/godgaji/gajiquiz/domain/Category/Category.java
  src/main/java/kr/godgaji/gajiquiz/domain/Category/CategoryRepository.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/Member.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/MemberRepository.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/Role.java
  src/main/java/kr/godgaji/gajiquiz/domain/Question/Question.java
  src/main/java/kr/godgaji/gajiquiz/domain/Question/QuestionRepository.java
  src/main/java/kr/godgaji/gajiquiz/domain/SolvedLog/SolvedLog.java
  src/main/java/kr/godgaji/gajiquiz/domain/SolvedLog/SolvedLogRepository.java
  src/main/resources/application.yml
  src/test/java/kr/godgaji/gajiquiz/domain/RoleTest.java
Labels: :banana: chore, :eggplant: feature

#29 style : banner 설정 [#28]
  src/main/resources/application-banner.yml
  src/main/resources/application.yml
  src/main/resources/banner.png
Labels: :tulip: style

#34 chore : local환경 mariadb설정, test환경 H2설정 [#18]
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/kr/godgaji/gajiquiz/GajiquizApplicationTests.java
  src/test/java/kr/godgaji/gajiquiz/domain/RoleTest.java
Labels: :banana: chore

#36 chore : develop, production 분리 [#35]
  src/main/resources/application-banner.yml
  src/main/resources/application-develop.yml
  src/main/resources/application-production.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: :banana: chore

#37 feat : Querydsl 설정 [#30]
  build.gradle
Labels: :eggplant: feature

#39 refactor : Spring Boot 버전 변경 [#38]
  build.gradle
Labels: :egg: refactor

#41 feat : Global Exception Handling 적용
  build.gradle
  src/main/java/kr/godgaji/gajiquiz/error/ErrorCode.java
  src/main/java/kr/godgaji/gajiquiz/error/ErrorResponse.java
  src/main/java/kr/godgaji/gajiquiz/error/FieldError.java
  src/main/java/kr/godgaji/gajiquiz/error/GlobalExceptionHandler.java
Labels: :eggplant: feature

#42 feat : 닉네임 저장기능 구현 [#27]
  build.gradle
  src/main/java/kr/godgaji/gajiquiz/config/SwaggerConfig.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/Member.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/MemberCustomRepository.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/MemberRepository.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/MemberRepositoryImpl.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/NickNameDuplicateValidator.java
  src/main/java/kr/godgaji/gajiquiz/domain/Member/NickNameUnique.java
  src/main/java/kr/godgaji/gajiquiz/service/member/MemberService.java
  src/main/java/kr/godgaji/gajiquiz/web/MemberController.java
  src/main/java/kr/godgaji/gajiquiz/web/dto/member/UpdateNickNameRequestDto.java
  src/main/java/kr/godgaji/gajiquiz/web/dto/member/UpdateNickNameResponseDto.java
  src/test/java/kr/godgaji/gajiquiz/service/MemberServiceTest.java
  src/test/java/kr/godgaji/gajiquiz/service/NickNameValidTest.java
Labels: :eggplant: feature

#44 feat : Jenkins CI 적용을 위한 Jenkinsfile 추가 [#43]
  .github/workflows/gradle.yml
  Jenkinsfile
  src/test/java/kr/godgaji/gajiquiz/GajiquizApplicationTests.java
Labels: :banana: chore, :egg: refactor

#46 docs : CI Build, Coverage Badge 추가 [#45]
  README.md
Labels: :memo: docs

#48 feat : 자동으로 도커 허브에 이미지 업로드
  Dockerfile
  Jenkinsfile
  scripts/docker-entrypoint.sh
  src/main/resources/application-develop.yml
Labels: :eggplant: feature
